package com.kvizo.app.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.State
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember

object StringProvider {
    val currentLang = mutableStateOf("en")

    fun setLanguage(lang: String) { currentLang.value = lang }

    fun t(key: String): String = translations[currentLang.value]?.get(key)
        ?: translations["en"]?.get(key)
        ?: key

    @Composable
    fun rememberT(key: String): State<String> {
        val lang = currentLang.value
        val value = translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
        return remember(lang, key) { mutableStateOf(value) }
    }

    private val translations = mapOf(
        "en" to mapOf(
            "home" to "Home", "quizzes" to "Quizzes", "create" to "Create",
            "stats" to "Stats", "profile" to "Profile", "settings" to "Settings",
            "notifications" to "Notifications", "no_notifications" to "No notifications yet",
            "close" to "Close", "back" to "Back", "save" to "Save", "cancel" to "Cancel",
            "edit_profile" to "Edit Profile", "username" to "Username",
            "status" to "Status", "bio" to "Bio", "avatar" to "Avatar",
            "sign_out" to "Sign Out", "sign_out_confirm" to "Are you sure you want to sign out?",
            "language" to "Language", "theme" to "Theme", "system" to "System",
            "light" to "Light", "dark" to "Dark", "sound_effects" to "Sound effects",
            "haptic_feedback" to "Haptic feedback", "backup_restore" to "Backup & Restore",
            "your_data_stays_yours" to "Your data stays yours",
            "backup" to "Backup", "restore" to "Restore",
            "back_up_all_data" to "Back up all data",
            "save_json_file" to "Save a JSON file with everything",
            "restore_from_json" to "Restore from JSON",
            "import_stats_badges" to "Import stats, badges & quizzes you made",
            "whats_included" to "What's included",
            "storage_used" to "Storage used", "reset_all_data" to "Reset all data",
            "reset" to "Reset", "updater" to "Updater", "changelog" to "Changelog",
            "about" to "About", "quick_actions" to "Quick actions",
            "popular_quizzes" to "Popular quizzes", "recent_quizzes" to "Recent quizzes",
            "no_quizzes_yet" to "No quizzes yet",
            "create_or_import" to "Create one or import a .txt file",
            "focus_area" to "Focus area", "below_60" to "is below 60% — keep practicing",
            "create_quiz" to "Create Quiz", "edit_quiz" to "Edit Quiz",
            "quiz_title" to "Quiz title *", "add_question" to "Add Question",
            "add_first_question" to "Add First Question",
            "no_questions_yet" to "No questions yet",
            "add_first_q_desc" to "Add your first question to start building this quiz",
            "save_draft" to "Save Draft", "publish_quiz" to "Publish Quiz",
            "preview" to "Preview", "import_code" to "Import quiz from code",
            "paste_share_code" to "Paste a share code to fill this builder.",
            "difficulty" to "Difficulty", "tags_optional" to "Tags (optional)",
            "add_tag" to "Add tag", "description" to "Description",
            "time_limit" to "Time limit", "none" to "None",
            "performance_difficulty" to "Performance by Difficulty",
            "my_quizzes" to "My Quizzes", "badges" to "Badges",
            "member_since" to "Member since", "level_progress" to "Level progress",
            "quizzes_created" to "quizzes created", "attempts_taken" to "attempts taken",
            "time_played" to "time played", "quizzes_today" to "quizzes today",
            "streak" to "Streak", "this_week" to "This week",
            "accuracy" to "accuracy", "days_in_a_row" to "days in a row",
            "on_fire" to "on fire!", "max_level" to "Max level reached",
            "category" to "Category", "science" to "Science",
            "mathematics" to "Mathematics", "history" to "History",
            "geography" to "Geography", "programming" to "Programming",
            "sports" to "Sports", "entertainment" to "Entertainment",
            "create_your_profile" to "Create Your Profile",
            "lets_get_started" to "Let's get started",
            "start_learning" to "Start Learning",
            "welcome_to_kvizo" to "Welcome to Kvizo",
            "welcome_back" to "Welcome back",
            "name" to "Name", "level" to "Level", "xp" to "XP",
            "play" to "Play", "review" to "Review",
            "retry" to "Retry", "next" to "Next", "finish" to "Finish",
            "score" to "Score", "correct" to "Correct", "incorrect" to "Incorrect",
            "time_up" to "Time's up!", "out_of" to "out of",
            "questions" to "questions", "great_job" to "Great job!",
            "keep_going" to "Keep going!", "try_again" to "Try again",
            "share" to "Share", "import" to "Import", "export" to "Export",
            "bookmarks" to "Bookmarks", "history" to "History",
            "search" to "Search", "filter" to "Filter", "sort" to "Sort",
            "all" to "All", "easy" to "Easy", "medium" to "Medium", "hard" to "Hard",
            "no_bookmarks" to "No bookmarks yet",
            "tap_star_to_bookmark" to "Tap the star icon to bookmark questions",
            "no_history" to "No history yet",
            "completed_quizzes_appear" to "Completed quizzes will appear here",
            "leaderboard" to "Leaderboard", "achievements" to "Achievements",
            "daily_goal" to "Daily Goal", "streak_days" to "Streak days",
            "total_xp" to "Total XP", "quizzes_completed" to "Quizzes completed",
            "average_score" to "Average score", "best_streak" to "Best streak",
            "rank" to "Rank", "points" to "Points", "trophies" to "Trophies",
            "level_up" to "Level Up!", "new_badge" to "New Badge!",
            "achievement_unlocked" to "Achievement unlocked!",
            "settings_saved" to "Settings saved",
            "profile_updated" to "Profile updated",
            "quiz_deleted" to "Quiz deleted",
            "quiz_duplicated" to "Quiz duplicated",
            "imported_successfully" to "Imported successfully",
            "exported_successfully" to "Exported successfully",
            "error_occurred" to "An error occurred",
            "try_later" to "Please try again later",
            "no_internet" to "No internet connection",
            "loading" to "Loading...",
                        "daily_quest" to "Daily Quest",
            "answer_5_math" to "Answer 5 Math Cards",
            "start" to "Start",
            "today" to "Today",
            "authored" to "Authored",
            "activity" to "Activity",
            "session" to "Session",
            "view_all" to "View all",
            "community_spotlight" to "Community Spotlight",
            "explore_labs" to "Explore Interactive Labs",
            "explore_labs_desc" to "Test your concepts with thousands of community flashcard sets and instant feedback.",
            "download_quizzes" to "Download Quizzes",
            "daily_streak" to "Daily Streak",
            "in" to "in",
            "total_quizzes" to "Total Quizzes",
            "total_questions" to "Total Questions",
            "complete_quizzes_unlock" to "Complete quizzes to unlock badges!",
            "your_quiz_will_appear" to "Your quizzes will appear here",
            "tap_to_start" to "Tap to start",
            "swipe_to_navigate" to "Swipe to navigate",
            "long_press_options" to "Long press for options",
            "shake_to_shuffle" to "Shake to shuffle",
            "double_tap_answer" to "Double tap to answer",
            "pinch_zoom" to "Pinch to zoom",
            "drag_reorder" to "Drag to reorder",
            "pull_refresh" to "Pull to refresh",
            "tap_to_expand" to "Tap to expand",
            "tap_to_collapse" to "Tap to collapse",
            "slide_to_adjust" to "Slide to adjust",
            "hold_to_record" to "Hold to record",
            "swipe_to_dismiss" to "Swipe to dismiss",
            "tap_to_select" to "Tap to select",
            "tap_to_deselect" to "Tap to deselect",
            "tap_to_toggle" to "Tap to toggle",
            "tap_to_switch" to "Tap to switch",
            "tap_to_change" to "Tap to change",
            "tap_to_update" to "Tap to update",
            "tap_to_edit" to "Tap to edit",
            "tap_to_delete" to "Tap to delete",
            "tap_to_add" to "Tap to add",
            "tap_to_remove" to "Tap to remove",
            "tap_to_open" to "Tap to open",
            "tap_to_close" to "Tap to close",
            "tap_to_show" to "Tap to show",
            "tap_to_hide" to "Tap to hide",
            "tap_to_enable" to "Tap to enable",
            "tap_to_disable" to "Tap to disable",
            "tap_to_start" to "Tap to start",
            "tap_to_stop" to "Tap to stop",
            "tap_to_pause" to "Tap to pause",
            "tap_to_resume" to "Tap to resume",
            "tap_to_restart" to "Tap to restart",
            "tap_to_refresh" to "Tap to refresh",
            "tap_to_reload" to "Tap to reload",
            "tap_to_retry" to "Tap to retry",
            "tap_to_continue" to "Tap to continue",
            "tap_to_proceed" to "Tap to proceed",
            "tap_to_confirm" to "Tap to confirm",
            "tap_to_cancel" to "Tap to cancel",
            "tap_to_accept" to "Tap to accept",
            "tap_to_decline" to "Tap to decline",
            "tap_to_agree" to "Tap to agree",
            "tap_to_disagree" to "Tap to disagree",
            "tap_to_approve" to "Tap to approve",
            "tap_to_reject" to "Tap to reject",
            "tap_to_allow" to "Tap to allow",
            "tap_to_deny" to "Tap to deny",
            "tap_to_grant" to "Tap to grant",
            "tap_to_revoke" to "Tap to revoke",
            "tap_to_trust" to "Tap to trust",
            "tap_to_block" to "Tap to block",
            "tap_to_unblock" to "Tap to unblock",
            "tap_to_follow" to "Tap to follow",
            "tap_to_unfollow" to "Tap to unfollow",
            "tap_to_subscribe" to "Tap to subscribe",
            "tap_to_unsubscribe" to "Tap to unsubscribe",
            "tap_to_mute" to "Tap to mute",
            "tap_to_unmute" to "Tap to unmute",
            "tap_to_pin" to "Tap to pin",
            "tap_to_unpin" to "Tap to unpin",
            "tap_to_lock" to "Tap to lock",
            "tap_to_unlock" to "Tap to unlock",
            "tap_to_freeze" to "Tap to freeze",
            "tap_to_unfreeze" to "Tap to unfreeze",
            "tap_to_archive" to "Tap to archive",
            "tap_to_unarchive" to "Tap to unarchive",
            "tap_to_save" to "Tap to save",
            "tap_to_discard" to "Tap to discard",
            "tap_to_apply" to "Tap to apply",
            "tap_to_reset" to "Tap to reset",
            "tap_to_undo" to "Tap to undo",
            "tap_to_redo" to "Tap to redo",
            "tap_to_copy" to "Tap to copy",
            "tap_to_paste" to "Tap to paste",
            "tap_to_cut" to "Tap to cut",
            "tap_to_select_all" to "Tap to select all",
            "tap_to_deselect_all" to "Tap to deselect all",
            "tap_to_invert_selection" to "Tap to invert selection",
            "tap_to_clear_selection" to "Tap to clear selection"
        ),
        "hi" to mapOf(
            "home" to "होम", "quizzes" to "क्विज़", "create" to "बनाएं",
            "stats" to "आंकड़े", "profile" to "प्रोफ़ाइल", "settings" to "सेटिंग्स",
            "notifications" to "सूचनाएं", "no_notifications" to "अभी कोई सूचना नहीं",
            "close" to "बंद करें", "back" to "वापस", "save" to "सहेजें", "cancel" to "रद्द करें",
            "edit_profile" to "प्रोफ़ाइल संपादित करें", "username" to "उपयोगकर्ता नाम",
            "status" to "स्थिति", "bio" to "बायो", "avatar" to "अवतार",
            "sign_out" to "साइन आउट", "sign_out_confirm" to "क्या आप साइन आउट करना चाहते हैं?",
            "language" to "भाषा", "theme" to "थीम", "system" to "सिस्टम",
            "light" to "लाइट", "dark" to "डार्क", "sound_effects" to "ध्वनि प्रभाव",
            "haptic_feedback" to "हैप्टिक फ़ीडबैक", "backup_restore" to "बैकअप और रिस्टोर",
            "your_data_stays_yours" to "आपका डेटा आपका है",
            "backup" to "बैकअप", "restore" to "रिस्टोर",
            "back_up_all_data" to "सारा डेटा बैकअप करें",
            "save_json_file" to "सब कुछ JSON फ़ाइल में सहेजें",
            "restore_from_json" to "JSON से रिस्टोर करें",
            "import_stats_badges" to "अपने स्टैट्स, बैज और क्विज़ इंपोर्ट करें",
            "whats_included" to "क्या-क्या शामिल है",
            "storage_used" to "स्टोरेज उपयोग", "reset_all_data" to "सारा डेटा रीसेट करें",
            "reset" to "रीसेट", "updater" to "अपडेटर", "changelog" to "चेंजलॉग",
            "about" to "ऐप के बारे में", "quick_actions" to "त्वरित क्रियाएं",
            "popular_quizzes" to "लोकप्रिय क्विज़", "recent_quizzes" to "हाल की क्विज़",
            "no_quizzes_yet" to "अभी कोई क्विज़ नहीं",
            "create_or_import" to "बनाएं या .txt फ़ाइल इंपोर्ट करें",
            "focus_area" to "ध्यान दें", "below_60" to "60% से कम है — अभ्यास जारी रखें",
            "create_quiz" to "क्विज़ बनाएं", "edit_quiz" to "क्विज़ संपादित करें",
            "quiz_title" to "क्विज़ शीर्षक *", "add_question" to "प्रश्न जोड़ें",
            "add_first_question" to "पहला प्रश्न जोड़ें",
            "no_questions_yet" to "अभी कोई प्रश्न नहीं",
            "add_first_q_desc" to "इस क्विज़ को बनाने के लिए पहला प्रश्न जोड़ें",
            "save_draft" to "ड्राफ्ट सहेजें", "publish_quiz" to "क्विज़ प्रकाशित करें",
            "preview" to "पूर्वावलोकन", "import_code" to "कोड से क्विज़ इंपोर्ट करें",
            "paste_share_code" to "बिल्डर भरने के लिए शेयर कोड पेस्ट करें।",
            "difficulty" to "कठिनाई", "tags_optional" to "टैग (वैकल्पिक)",
            "add_tag" to "टैग जोड़ें", "description" to "विवरण",
            "time_limit" to "समय सीमा", "none" to "कोई नहीं",
            "performance_difficulty" to "कठिनाई के अनुसार प्रदर्शन",
            "my_quizzes" to "मेरी क्विज़", "badges" to "बैज",
            "member_since" to "सदस्य बने", "level_progress" to "स्तर प्रगति",
            "streak" to "स्ट्रीक", "this_week" to "इस सप्ताह",
            "accuracy" to "सटीकता", "days_in_a_row" to "लगातार दिन",
            "on_fire" to "ज़बरदस्त!", "max_level" to "अधिकतम स्तर पहुँच गया",
            "category" to "श्रेणी", "science" to "विज्ञान",
            "mathematics" to "गणित", "history" to "इतिहास",
            "geography" to "भूगोल", "programming" to "प्रोग्रामिंग",
            "sports" to "खेल", "entertainment" to "मनोरंजन",
            "welcome_to_kvizo" to "क्विज़ो में आपका स्वागत है",
            "start_learning" to "सीखना शुरू करें",
            "play" to "खेलें", "review" to "समीक्षा",
            "retry" to "पुनः प्रयास करें", "next" to "अगला", "finish" to "समाप्त",
            "score" to "स्कोर", "correct" to "सही", "incorrect" to "गलत",
            "time_up" to "समय समाप्त!", "out_of" to "में से",
            "questions" to "प्रश्न", "great_job" to "बहुत अच्छा!",
            "keep_going" to "जारी रखें!", "try_again" to "फिर से प्रयास करें",
            "share" to "साझा करें", "import" to "इंपोर्ट", "export" to "एक्सपोर्ट",
            "bookmarks" to "बुकमार्क", "history" to "इतिहास",
            "search" to "खोजें", "filter" to "फ़िल्टर", "sort" to "क्रमबद्ध करें",
            "all" to "सभी", "easy" to "आसान", "medium" to "मध्यम", "hard" to "कठिन",
            "no_bookmarks" to "अभी कोई बुकमार्क नहीं",
            "tap_star_to_bookmark" to "बुकमार्क के लिए स्टार आइकन टैप करें",
            "no_history" to "अभी कोई इतिहास नहीं",
            "completed_quizzes_appear" to "पूरी की गई क्विज़ यहाँ दिखेंगी",
            "leaderboard" to "लीडरबोर्ड", "achievements" to "उपलब्धियां",
            "daily_goal" to "दैनिक लक्ष्य", "streak_days" to "स्ट्रीक दिन",
            "total_xp" to "कुल XP", "quizzes_completed" to "क्विज़ पूरी",
            "average_score" to "औसत स्कोर", "best_streak" to "सर्वश्रेष्ठ स्ट्रीक",
            "rank" to "रैंक", "points" to "अंक", "trophies" to "ट्रॉफियां",
            "level_up" to "स्तर बढ़ा!", "new_badge" to "नया बैज!",
            "achievement_unlocked" to "उपलब्धि अनलॉक!",
            "settings_saved" to "सेटिंग्स सहेजी गईं",
            "profile_updated" to "प्रोफ़ाइल अपडेट हुई",
            "quiz_deleted" to "क्विज़ हटाई गई",
            "quiz_duplicated" to "क्विज़ डुप्लिकेट हुई",
            "imported_successfully" to "सफलतापूर्वक इंपोर्ट हुआ",
            "exported_successfully" to "सफलतापूर्वक एक्सपोर्ट हुआ",
            "error_occurred" to "एक त्रुटि हुई",
            "try_later" to "कृपया बाद में पुनः प्रयास करें",
            "no_internet" to "इंटरनेट कनेक्शन नहीं है",
            "loading" to "लोड हो रहा है...",
            "tap_to_start" to "शुरू करने के लिए टैप करें",
            "daily_quest" to "दैनिक क्वेस्ट",
            "answer_5_math" to "5 गणित कार्डस का उत्तर दें",
            "start" to "शुरू करें",
            "today" to "आज",
            "quizzes_today" to "आज क्विज़",
            "authored" to "बनाई गई",
            "quizzes_created" to "क्विज़ बनाई",
            "activity" to "गतिविधि",
            "attempts_taken" to "प्रयास किए",
            "session" to "सत्र",
            "time_played" to "समय खेला",
            "view_all" to "सभी देखें",
            "community_spotlight" to "सामुदायिक स्पॉटलाइट",
            "explore_labs" to "इंटरैक्टिव लैब्स खोजें",
            "daily_streak" to "दैनिक स्ट्रीक",
            "in" to "में",
            "total_quizzes" to "कुल क्विज़",
            "total_questions" to "कुल प्रश्न",
            "explore_labs_desc" to "हजारों कम्युनिटी फ़्लैशकार्ड सेट्स से अपनी अवधारणाओं का परीक्षण करें।",
            "download_quizzes" to "क्विज़ डाउनलोड करें",
            "complete_quizzes_unlock" to "बैज अनलॉक करने के लिए क्विज़ पूरी करें!",
            "your_quiz_will_appear" to "आपकी क्विज़ यहाँ दिखेंगी",
                ),
        "zh" to mapOf(
            "home" to "首页", "quizzes" to "测验", "create" to "创建",
            "stats" to "统计", "profile" to "个人资料", "settings" to "设置",
            "notifications" to "通知", "no_notifications" to "暂无通知",
            "close" to "关闭", "back" to "返回", "save" to "保存", "cancel" to "取消",
            "edit_profile" to "编辑个人资料", "username" to "用户名",
            "status" to "状态", "bio" to "简介", "avatar" to "头像",
            "sign_out" to "退出登录", "sign_out_confirm" to "确定要退出登录吗？",
            "language" to "语言", "theme" to "主题", "system" to "系统",
            "light" to "浅色", "dark" to "深色", "sound_effects" to "音效",
            "haptic_feedback" to "触觉反馈", "backup_restore" to "备份与恢复",
            "your_data_stays_yours" to "您的数据属于您",
            "backup" to "备份", "restore" to "恢复",
            "back_up_all_data" to "备份所有数据",
            "save_json_file" to "将所有内容保存为JSON文件",
            "restore_from_json" to "从JSON恢复",
            "import_stats_badges" to "导入您的统计、徽章和测验",
            "whats_included" to "包含内容",
            "storage_used" to "已用存储", "reset_all_data" to "重置所有数据",
            "reset" to "重置", "updater" to "更新器", "changelog" to "更新日志",
            "about" to "关于", "quick_actions" to "快捷操作",
            "popular_quizzes" to "热门测验", "recent_quizzes" to "最近测验",
            "no_quizzes_yet" to "暂无测验",
            "create_or_import" to "创建一个或导入.txt文件",
            "focus_area" to "重点关注", "below_60" to "低于60% — 继续练习",
            "create_quiz" to "创建测验", "edit_quiz" to "编辑测验",
            "quiz_title" to "测验标题 *", "add_question" to "添加问题",
            "add_first_question" to "添加第一个问题",
            "no_questions_yet" to "暂无问题",
            "add_first_q_desc" to "添加第一个问题来开始构建此测验",
            "save_draft" to "保存草稿", "publish_quiz" to "发布测验",
            "preview" to "预览", "import_code" to "通过代码导入测验",
            "paste_share_code" to "粘贴分享代码以填充此构建器。",
            "difficulty" to "难度", "tags_optional" to "标签（可选）",
            "add_tag" to "添加标签", "description" to "描述",
            "time_limit" to "时间限制", "none" to "无",
            "performance_difficulty" to "按难度表现",
            "my_quizzes" to "我的测验", "badges" to "徽章",
            "member_since" to "注册于", "level_progress" to "等级进度",
            "streak" to "连续", "this_week" to "本周",
            "accuracy" to "正确率", "days_in_a_row" to "连续天数",
            "on_fire" to "太棒了!", "max_level" to "已达最高等级",
            "category" to "类别", "science" to "科学",
            "mathematics" to "数学", "history" to "历史",
            "geography" to "地理", "programming" to "编程",
            "sports" to "体育", "entertainment" to "娱乐",
            "welcome_to_kvizo" to "欢迎来到 Kvizo",
            "start_learning" to "开始学习",
            "play" to "开始", "review" to "复习",
            "score" to "分数", "correct" to "正确", "incorrect" to "错误",
            "time_up" to "时间到!", "great_job" to "做得好!",
            "share" to "分享", "import" to "导入", "export" to "导出",
            "bookmarks" to "书签", "search" to "搜索",
            "all" to "全部", "easy" to "简单", "medium" to "中等", "hard" to "困难",
            "daily_quest" to "每日任务",
            "answer_5_math" to "回答5道数学题",
            "start" to "开始",
            "today" to "今天",
            "quizzes_today" to "今日测验",
            "authored" to "已创建",
            "quizzes_created" to "创建的测验",
            "activity" to "活动",
            "attempts_taken" to "尝试次数",
            "session" to "会话",
            "time_played" to "游戏时间",
            "view_all" to "查看全部",
            "community_spotlight" to "社区聚焦",
            "explore_labs" to "探索互动实验室",
            "daily_streak" to "每日连胜",
            "in" to "还需",
            "total_quizzes" to "总测验数",
            "total_questions" to "总题目数",
            "explore_labs_desc" to "通过数千套社区闪卡和即时反馈测试您的概念。",
            "download_quizzes" to "下载测验",
            "complete_quizzes_unlock" to "完成测验以解锁徽章！",
            "your_quiz_will_appear" to "您的测验将显示在这里",
                ),
        "es" to mapOf(
            "home" to "Inicio", "quizzes" to "Cuestionarios", "create" to "Crear",
            "stats" to "Estadísticas", "profile" to "Perfil", "settings" to "Ajustes",
            "notifications" to "Notificaciones", "no_notifications" to "Sin notificaciones",
            "close" to "Cerrar", "back" to "Volver", "save" to "Guardar", "cancel" to "Cancelar",
            "edit_profile" to "Editar perfil", "username" to "Nombre de usuario",
            "status" to "Estado", "bio" to "Biografía", "avatar" to "Avatar",
            "sign_out" to "Cerrar sesión", "sign_out_confirm" to "¿Seguro que quieres cerrar sesión?",
            "language" to "Idioma", "theme" to "Tema", "system" to "Sistema",
            "light" to "Claro", "dark" to "Oscuro", "sound_effects" to "Efectos de sonido",
            "haptic_feedback" to "Respuesta háptica", "backup_restore" to "Copia de seguridad y restauración",
            "your_data_stays_yours" to "Tus datos son tuyos",
            "backup" to "Copia de seguridad", "restore" to "Restaurar",
            "back_up_all_data" to "Copia de seguridad de todo",
            "save_json_file" to "Guardar todo en un archivo JSON",
            "restore_from_json" to "Restaurar desde JSON",
            "import_stats_badges" to "Importar estadísticas, insignias y cuestionarios",
            "whats_included" to "Qué incluye",
            "storage_used" to "Almacenamiento usado", "reset_all_data" to "Restablecer todos los datos",
            "reset" to "Restablecer", "updater" to "Actualizador", "changelog" to "Registro de cambios",
            "about" to "Acerca de", "quick_actions" to "Acciones rápidas",
            "popular_quizzes" to "Cuestionarios populares", "recent_quizzes" to "Cuestionarios recientes",
            "no_quizzes_yet" to "Aún no hay cuestionarios",
            "create_or_import" to "Crea uno o importa un archivo .txt",
            "focus_area" to "Área de enfoque", "below_60" to "por debajo del 60% — sigue practicando",
            "create_quiz" to "Crear cuestionario", "edit_quiz" to "Editar cuestionario",
            "quiz_title" to "Título del cuestionario *", "add_question" to "Agregar pregunta",
            "add_first_question" to "Agregar primera pregunta",
            "no_questions_yet" to "Aún no hay preguntas",
            "add_first_q_desc" to "Agrega tu primera pregunta para empezar",
            "save_draft" to "Guardar borrador", "publish_quiz" to "Publicar cuestionario",
            "preview" to "Vista previa", "import_code" to "Importar desde código",
            "paste_share_code" to "Pega un código para llenar este editor.",
            "difficulty" to "Dificultad", "tags_optional" to "Etiquetas (opcional)",
            "add_tag" to "Agregar etiqueta", "description" to "Descripción",
            "time_limit" to "Límite de tiempo", "none" to "Ninguno",
            "performance_difficulty" to "Rendimiento por dificultad",
            "my_quizzes" to "Mis cuestionarios", "badges" to "Insignias",
            "member_since" to "Miembro desde", "level_progress" to "Progreso de nivel",
            "streak" to "Racha", "this_week" to "Esta semana",
            "accuracy" to "precisión", "days_in_a_row" to "días seguidos",
            "on_fire" to "¡increíble!", "max_level" to "Nivel máximo alcanzado",
            "category" to "Categoría", "science" to "Ciencia",
            "mathematics" to "Matemáticas", "history" to "Historia",
            "geography" to "Geografía", "programming" to "Programación",
            "sports" to "Deportes", "entertainment" to "Entretenimiento",
            "welcome_to_kvizo" to "Bienvenido a Kvizo",
            "start_learning" to "Empezar a aprender",
            "play" to "Jugar", "review" to "Revisar",
            "score" to "Puntuación", "correct" to "Correcto", "incorrect" to "Incorrecto",
            "time_up" to "¡Tiempo!", "great_job" to "¡Buen trabajo!",
            "share" to "Compartir", "import" to "Importar", "export" to "Exportar",
            "bookmarks" to "Marcadores", "search" to "Buscar",
            "all" to "Todos", "easy" to "Fácil", "medium" to "Medio", "hard" to "Difícil",
            "daily_quest" to "Misión diaria",
            "answer_5_math" to "Responde 5 cartas de matemáticas",
            "start" to "Empezar",
            "today" to "Hoy",
            "quizzes_today" to "Cuestionarios hoy",
            "authored" to "Creadas",
            "quizzes_created" to "Cuestionarios creados",
            "activity" to "Actividad",
            "attempts_taken" to "Intentos realizados",
            "session" to "Sesión",
            "time_played" to "Tiempo jugado",
            "view_all" to "Ver todo",
            "community_spotlight" to "Destacado de la comunidad",
            "explore_labs" to "Explora laboratorios interactivos",
            "daily_streak" to "Racha diaria",
            "in" to "en",
            "total_quizzes" to "Total de cuestionarios",
            "total_questions" to "Total de preguntas",
            "explore_labs_desc" to "Pon a prueba tus conceptos con miles de conjuntos de tarjetas de la comunidad.",
            "download_quizzes" to "Descargar Cuestionarios",
            "complete_quizzes_unlock" to "¡Completa cuestionarios para desbloquear insignias!",
            "your_quiz_will_appear" to "Tus cuestionarios aparecerán aquí",
                ),
        "fr" to mapOf(
            "home" to "Accueil", "quizzes" to "Quiz", "create" to "Créer",
            "stats" to "Statistiques", "profile" to "Profil", "settings" to "Paramètres",
            "notifications" to "Notifications", "no_notifications" to "Pas encore de notifications",
            "close" to "Fermer", "back" to "Retour", "save" to "Enregistrer", "cancel" to "Annuler",
            "edit_profile" to "Modifier le profil", "username" to "Nom d utilisateur",
            "status" to "Statut", "bio" to "Bio", "avatar" to "Avatar",
            "sign_out" to "Déconnexion", "sign_out_confirm" to "Voulez-vous vraiment vous déconnecter?",
            "language" to "Langue", "theme" to "Thème", "system" to "Système",
            "light" to "Clair", "dark" to "Sombre", "sound_effects" to "Effets sonores",
            "haptic_feedback" to "Retour haptique", "backup_restore" to "Sauvegarde et restauration",
            "your_data_stays_yours" to "Vos données vous appartiennent",
            "backup" to "Sauvegarde", "restore" to "Restaurer",
            "back_up_all_data" to "Sauvegarder toutes les données",
            "save_json_file" to "Tout sauvegarder dans un fichier JSON",
            "restore_from_json" to "Restaurer depuis JSON",
            "import_stats_badges" to "Importer vos statistiques, badges et quiz",
            "whats_included" to "Ce qui est inclus",
            "storage_used" to "Stockage utilisé", "reset_all_data" to "Réinitialiser toutes les données",
            "reset" to "Réinitialiser", "updater" to "Mise à jour", "changelog" to "Journal des modifications",
            "about" to "À propos", "quick_actions" to "Actions rapides",
            "popular_quizzes" to "Quiz populaires", "recent_quizzes" to "Quiz récents",
            "no_quizzes_yet" to "Pas encore de quiz",
            "create_or_import" to "Créez-en un ou importez un fichier .txt",
            "focus_area" to "Domaine à améliorer", "below_60" to "en dessous de 60% — continuez à pratiquer",
            "create_quiz" to "Créer un quiz", "edit_quiz" to "Modifier le quiz",
            "quiz_title" to "Titre du quiz *", "add_question" to "Ajouter une question",
            "add_first_question" to "Ajouter la première question",
            "no_questions_yet" to "Pas encore de questions",
            "add_first_q_desc" to "Ajoutez votre première question pour commencer",
            "save_draft" to "Enregistrer le brouillon", "publish_quiz" to "Publier le quiz",
            "preview" to "Aperçu", "import_code" to "Importer depuis un code",
            "paste_share_code" to "Collez un code de partage pour remplir ce constructeur.",
            "difficulty" to "Difficulté", "tags_optional" to "Tags (optionnel)",
            "add_tag" to "Ajouter un tag", "description" to "Description",
            "time_limit" to "Limite de temps", "none" to "Aucune",
            "performance_difficulty" to "Performance par difficulté",
            "my_quizzes" to "Mes quiz", "badges" to "Badges",
            "member_since" to "Membre depuis", "level_progress" to "Progression du niveau",
            "streak" to "Série", "this_week" to "Cette semaine",
            "accuracy" to "précision", "days_in_a_row" to "jours consécutifs",
            "on_fire" to "incroyable!", "max_level" to "Niveau maximum atteint",
            "category" to "Catégorie", "science" to "Science",
            "mathematics" to "Mathématiques", "history" to "Histoire",
            "geography" to "Géographie", "programming" to "Programmation",
            "sports" to "Sports", "entertainment" to "Divertissement",
            "welcome_to_kvizo" to "Bienvenue sur Kvizo",
            "start_learning" to "Commencer à apprendre",
            "play" to "Jouer", "review" to "Revoir",
            "score" to "Score", "correct" to "Correct", "incorrect" to "Incorrect",
            "time_up" to "Temps écoulé!", "great_job" to "Bon travail!",
            "share" to "Partager", "import" to "Importer", "export" to "Exporter",
            "bookmarks" to "Signets", "search" to "Rechercher",
            "all" to "Tous", "easy" to "Facile", "medium" to "Moyen", "hard" to "Difficile",
            "daily_quest" to "Quête quotidienne",
            "answer_5_math" to "Réponds à 5 cartes de maths",
            "start" to "Commencer",
            "today" to "Aujourd'hui",
            "quizzes_today" to "Quiz aujourd'hui",
            "authored" to "Créés",
            "quizzes_created" to "Quiz créés",
            "activity" to "Activité",
            "attempts_taken" to "Tentatives effectuées",
            "session" to "Session",
            "time_played" to "Temps joué",
            "view_all" to "Voir tout",
            "community_spotlight" to "À la une de la communauté",
            "explore_labs" to "Explorez les laboratoires interactifs",
            "daily_streak" to "Série quotidienne",
            "in" to "dans",
            "total_quizzes" to "Total des quiz",
            "total_questions" to "Total des questions",
            "explore_labs_desc" to "Testez vos concepts avec des milliers de séries de cartes communautaires.",
            "download_quizzes" to "Télécharger les Quiz",
            "complete_quizzes_unlock" to "Complétez des quiz pour débloquer des badges !",
            "your_quiz_will_appear" to "Vos quiz apparaîtront ici",
        )
    )
}
