package com.quizforge.app.ui.components

import android.content.Context
import android.content.SharedPreferences

/**
 * Lightweight in-app localization for Kvizo.
 * 8 languages: en, hi, ta, te, bn, fr, es, de
 * Usage: L.s("start_learning")  → localized string (English fallback)
 * Language persisted in shared prefs; changes instantly (recomposition via State).
 */
object L {
    const val PREFS = "kvizo_lang"
    const val KEY = "lang"

    private var current: String = "en"

    val LANGUAGES = listOf(
        "en" to "English",
        "hi" to "हिन्दी",
        "ta" to "தமிழ்",
        "te" to "తెలుగు",
        "bn" to "বাংলা",
        "fr" to "Français",
        "es" to "Español",
        "de" to "Deutsch",
    )

    fun load(ctx: Context) {
        val p: SharedPreferences = ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        current = p.getString(KEY, "en") ?: "en"
    }

    fun currentLang(): String = current

    fun setLang(ctx: Context, lang: String) {
        current = lang
        ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit().putString(KEY, lang).apply()
    }

    private val en = mapOf(
        // Profile setup
        "welcome" to "Welcome to Kvizo",
        "no_login_needed" to "Create your local profile — no login needed",
        "pick_avatar" to "Pick an avatar",
        "username" to "Username",
        "status_optional" to "Status (optional)",
        "status_hint" to "e.g. Quiz Master",
        "bio_optional" to "Bio (optional, max 150)",
        "start_learning" to "Start Learning",
        "err_username_required" to "Username is required",
        "avatar" to "Avatar",
        // Profile
        "edit_profile" to "Edit Profile",
        "status_eg" to "Status (e.g. Quiz Master)",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "level" to "Level",
        "xp" to "XP",
        "stats" to "Stats",
        "quizzes_taken" to "Quizzes taken",
        "accuracy" to "Accuracy",
        "best_score" to "Best score",
        // Dashboard
        "home" to "Home",
        "start_quiz" to "Start Quiz",
        "create_quiz" to "Create Quiz",
        "community" to "Community",
        "leaderboard" to "Leaderboard",
        "my_quizzes" to "My Quizzes",
        "recent_quizzes" to "Recent Quizzes",
        "no_quizzes" to "No quizzes yet",
        "search_quizzes" to "Search quizzes...",
        // Quiz play
        "question" to "Question",
        "submit" to "Submit",
        "next" to "Next",
        "skip" to "Skip",
        "correct" to "Correct!",
        "wrong" to "Wrong!",
        "score" to "Score",
        "finish" to "Finish",
        "quiz_complete" to "Quiz Complete",
        "your_score" to "Your score",
        "play_again" to "Play Again",
        // Builder
        "quiz_title" to "Quiz Title",
        "add_question" to "Add Question",
        "option" to "Option",
        "correct_answer" to "Correct answer",
        "publish" to "Publish",
        // Settings
        "settings" to "Settings",
        "sound" to "Sound",
        "haptics" to "Haptics",
        "language" to "Language",
        "backup" to "Backup",
        "restore" to "Restore",
        "about" to "About",
        "version" to "Version",
        "check_updates" to "Check for updates",
        // Community
        "import_quiz" to "Import Quiz",
        "paste_url" to "Paste community URL",
        "import" to "Import",
        "verified" to "Verified",
        // Misc
        "yes" to "Yes",
        "no" to "No",
        "ok" to "OK",
        "loading" to "Loading...",
        "back" to "Back",

        "create_or_import" to "Create one or import a .txt file",
        "streak" to "Streak",
        "total_time" to "Total time",
        "your_answers" to "Your Answers",
        "badge_unlocked" to "Badge unlocked!",
        "question_navigator" to "Question Navigator",
        "flagged" to "Flagged",
        "error_loading" to "Error loading quizzes",
        "retry" to "Retry",
        "no_profiles" to "No profiles yet",
        "reset_data" to "Reset all data?",
        "delete_everything" to "Delete everything",
        "made_by" to "Made by SirYadav1",
        "time_limit" to "Time limit (seconds)",
        "review" to "Review",
        "reset" to "Reset",
    )

    private val hi = mapOf(
        "welcome" to "Kvizo में स्वागत है",
        "no_login_needed" to "अपनी लोकल प्रोफ़ाइल बनाएं — लॉगिन की ज़रूरत नहीं",
        "pick_avatar" to "अवतार चुनें",
        "username" to "यूज़रनेम",
        "status_optional" to "स्टेटस (वैकल्पिक)",
        "status_hint" to "जैसे: क्विज़ मास्टर",
        "bio_optional" to "बायो (वैकल्पिक, अधिकतम 150)",
        "start_learning" to "सीखना शुरू करें",
        "err_username_required" to "यूज़रनेम ज़रूरी है",
        "avatar" to "अवतार",
        "edit_profile" to "प्रोफ़ाइल एडिट करें",
        "status_eg" to "स्टेटस (जैसे: क्विज़ मास्टर)",
        "save" to "सेव",
        "cancel" to "रद्द करें",
        "delete" to "डिलीट",
        "level" to "लेवल",
        "xp" to "XP",
        "stats" to "आंकड़े",
        "quizzes_taken" to "किए गए क्विज़",
        "accuracy" to "सटीकता",
        "best_score" to "बेस्ट स्कोर",
        "home" to "होम",
        "start_quiz" to "क्विज़ शुरू करें",
        "create_quiz" to "क्विज़ बनाएं",
        "community" to "कम्युनिटी",
        "leaderboard" to "लीडरबोर्ड",
        "my_quizzes" to "मेरे क्विज़",
        "recent_quizzes" to "हाल के क्विज़",
        "no_quizzes" to "अभी कोई क्विज़ नहीं",
        "search_quizzes" to "क्विज़ खोजें...",
        "question" to "सवाल",
        "submit" to "सबमिट",
        "next" to "आगे",
        "skip" to "छोड़ें",
        "correct" to "सही!",
        "wrong" to "गलत!",
        "score" to "स्कोर",
        "finish" to "पूरा करें",
        "quiz_complete" to "क्विज़ पूरा!",
        "your_score" to "तुम्हारा स्कोर",
        "play_again" to "फिर से खेलें",
        "quiz_title" to "क्विज़ टाइटल",
        "add_question" to "सवाल जोड़ें",
        "option" to "विकल्प",
        "correct_answer" to "सही जवाब",
        "publish" to "पब्लिश",
        "settings" to "सेटिंग्स",
        "sound" to "ध्वनि",
        "haptics" to "हैप्टिक्स",
        "language" to "भाषा",
        "backup" to "बैकअप",
        "restore" to "रिस्टोर",
        "about" to "ऐप के बारे में",
        "version" to "वर्ज़न",
        "check_updates" to "अपडेट जांचें",
        "import_quiz" to "क्विज़ इंपोर्ट करें",
        "paste_url" to "कम्युनिटी URL पेस्ट करें",
        "import" to "इंपोर्ट",
        "verified" to "वेरिफाइड",
        "yes" to "हां",
        "no" to "नहीं",
        "ok" to "ठीक है",
        "loading" to "लोड हो रहा है...",
        "back" to "वापस",
        "create_or_import" to "एक बनाएं या .txt फाइल इंपोर्ट करें",
        "streak" to "स्ट्रीक",
        "total_time" to "कुल समय",
        "your_answers" to "तुम्हारे जवाब",
        "badge_unlocked" to "बैज अनलॉक!",
        "question_navigator" to "सवाल नेविगेटर",
        "flagged" to "फ्लैग किया",
        "error_loading" to "क्विज़ लोड में त्रुटि",
        "retry" to "फिर कोशिश",
        "no_profiles" to "अभी कोई प्रोफ़ाइल नहीं",
        "reset_data" to "सारा डेटा रीसेट करें?",
        "delete_everything" to "सब कुछ डिलीट करें",
        "made_by" to "बनाया गया SirYadav1 द्वारा",
        "time_limit" to "समय सीमा (सेकंड)",
        "review" to "समीक्षा",
        "reset" to "रीसेट",
    )

    private val ta = mapOf(
        "welcome" to "Kvizo-க்கு வரவேற்கிறோம்",
        "no_login_needed" to "உங்கள் உள்ளூர் சுயவிவரத்தை உருவாக்குங்கள் — உள்நுழைவு தேவையில்லை",
        "pick_avatar" to "அவதாரம் தேர்வு",
        "username" to "பயனர்பெயர்",
        "status_optional" to "நிலை (விருப்பம்)",
        "status_hint" to "உதா: குவிஸ் மாஸ்டர்",
        "bio_optional" to "சுயவிவரம் (விருப்பம், அதிகபட்சம் 150)",
        "start_learning" to "கற்றல் தொடங்கு",
        "err_username_required" to "பயனர்பெயர் தேவை",
        "avatar" to "அவதாரம்",
        "edit_profile" to "சுயவிவரத்தைத் திருத்து",
        "save" to "சேமி",
        "cancel" to "ரத்து",
        "delete" to "நீக்கு",
        "level" to "நிலை",
        "stats" to "புள்ளிவிவரம்",
        "home" to "முகப்பு",
        "start_quiz" to "குவிஸ் தொடங்கு",
        "create_quiz" to "குவிஸ் உருவாக்கு",
        "community" to "சமூகம்",
        "leaderboard" to "தரவரிசை",
        "my_quizzes" to "என் குவிஸ்கள்",
        "question" to "கேள்வி",
        "submit" to "சமர்ப்பி",
        "next" to "அடுத்து",
        "correct" to "சரி!",
        "wrong" to "தவறு!",
        "score" to "மதிப்பெண்",
        "quiz_complete" to "குவிஸ் முடிந்தது",
        "play_again" to "மீண்டும் விளையாடு",
        "settings" to "அமைப்புகள்",
        "sound" to "ஒலி",
        "haptics" to "ஹாப்டிக்ஸ்",
        "language" to "மொழி",
        "yes" to "ஆம்",
        "no" to "இல்லை",
        "ok" to "சரி",
        "loading" to "ஏற்றுகிறது...",
        "back" to "பின்",
    )

    private val te = mapOf(
        "welcome" to "Kvizoకి స్వాగతం",
        "no_login_needed" to "మీ లోకల్ ప్రొఫైల్ సృష్టించండి — లాగిన్ అవసరం లేదు",
        "pick_avatar" to "అవతార్ ఎంచుకోండి",
        "username" to "యూజర్‌పేరు",
        "status_optional" to "స్థితి (ఐచ్ఛికం)",
        "status_hint" to "ఉదా: క్విజ్ మాస్టర్",
        "start_learning" to "నేర్చుకోవడం ప్రారంభించండి",
        "err_username_required" to "యూజర్‌పేరు అవసరం",
        "avatar" to "అవతార్",
        "edit_profile" to "ప్రొఫైల్ ఎడిట్",
        "save" to "సేవ్",
        "cancel" to "రద్దు",
        "delete" to "డిలీట్",
        "level" to "లెవెల్",
        "stats" to "గణాంకాలు",
        "home" to "హోమ్",
        "start_quiz" to "క్విజ్ ప్రారంభించండి",
        "create_quiz" to "క్విజ్ సృష్టించండి",
        "community" to "కమ్యూనిటీ",
        "leaderboard" to "లీడర్‌బోర్డ్",
        "my_quizzes" to "నా క్విజ్‌లు",
        "question" to "ప్రశ్న",
        "submit" to "సబ్మిట్",
        "next" to "తర్వాత",
        "correct" to "సరైనది!",
        "wrong" to "తప్పు!",
        "score" to "స్కోరు",
        "quiz_complete" to "క్విజ్ పూర్తి!",
        "play_again" to "మళ్ళీ ఆడండి",
        "settings" to "సెట్టింగ్‌లు",
        "sound" to "ధ్వని",
        "haptics" to "హాప్టిక్స్",
        "language" to "భాష",
        "yes" to "అవును",
        "no" to "కాదు",
        "ok" to "సరే",
        "loading" to "లోడ్ అవుతోంది...",
        "back" to "వెనుక",
    )

    private val bn = mapOf(
        "welcome" to "Kvizo-তে স্বাগতম",
        "no_login_needed" to "আপনার লোকাল প্রোফাইল তৈরি করুন — লগইন দরকার নেই",
        "pick_avatar" to "অবতার বাছুন",
        "username" to "ইউজারনেম",
        "status_optional" to "স্ট্যাটাস (ঐচ্ছিক)",
        "status_hint" to "যেমন: কুইজ মাস্টার",
        "start_learning" to "শেখা শুরু করুন",
        "err_username_required" to "ইউজারনেম দরকার",
        "avatar" to "অবতার",
        "edit_profile" to "প্রোফাইল সম্পাদনা",
        "save" to "সেভ",
        "cancel" to "বাতিল",
        "delete" to "ডিলিট",
        "level" to "লেভেল",
        "stats" to "পরিসংখ্যান",
        "home" to "হোম",
        "start_quiz" to "কুইজ শুরু",
        "create_quiz" to "কুইজ বানান",
        "community" to "কমিউনিটি",
        "leaderboard" to "লিডারবোর্ড",
        "my_quizzes" to "আমার কুইজ",
        "question" to "প্রশ্ন",
        "submit" to "জমা দিন",
        "next" to "পরবর্তী",
        "correct" to "ঠিক!",
        "wrong" to "ভুল!",
        "score" to "স্কোর",
        "quiz_complete" to "কুইজ শেষ!",
        "play_again" to "আবার খেলুন",
        "settings" to "সেটিংস",
        "sound" to "শব্দ",
        "haptics" to "হ্যাপটিক্স",
        "language" to "ভাষা",
        "yes" to "হ্যাঁ",
        "no" to "না",
        "ok" to "ঠিক আছে",
        "loading" to "লোড হচ্ছে...",
        "back" to "পিছনে",
    )

    private val fr = mapOf(
        "welcome" to "Bienvenue sur Kvizo",
        "no_login_needed" to "Créez votre profil local — pas de connexion requise",
        "pick_avatar" to "Choisissez un avatar",
        "username" to "Nom d'utilisateur",
        "status_optional" to "Statut (optionnel)",
        "status_hint" to "ex. Maître du Quiz",
        "bio_optional" to "Bio (optionnel, max 150)",
        "start_learning" to "Commencer à apprendre",
        "err_username_required" to "Nom d'utilisateur requis",
        "avatar" to "Avatar",
        "edit_profile" to "Modifier le profil",
        "status_eg" to "Statut (ex. Maître du Quiz)",
        "save" to "Enregistrer",
        "cancel" to "Annuler",
        "delete" to "Supprimer",
        "level" to "Niveau",
        "xp" to "XP",
        "stats" to "Statistiques",
        "quizzes_taken" to "Quiz effectués",
        "accuracy" to "Précision",
        "best_score" to "Meilleur score",
        "home" to "Accueil",
        "start_quiz" to "Démarrer le quiz",
        "create_quiz" to "Créer un quiz",
        "community" to "Communauté",
        "leaderboard" to "Classement",
        "my_quizzes" to "Mes quiz",
        "recent_quizzes" to "Quiz récents",
        "no_quizzes" to "Aucun quiz pour le moment",
        "search_quizzes" to "Rechercher des quiz...",
        "question" to "Question",
        "submit" to "Soumettre",
        "next" to "Suivant",
        "skip" to "Passer",
        "correct" to "Correct !",
        "wrong" to "Faux !",
        "score" to "Score",
        "finish" to "Terminer",
        "quiz_complete" to "Quiz terminé",
        "your_score" to "Votre score",
        "play_again" to "Rejouer",
        "quiz_title" to "Titre du quiz",
        "add_question" to "Ajouter une question",
        "option" to "Option",
        "correct_answer" to "Bonne réponse",
        "publish" to "Publier",
        "settings" to "Paramètres",
        "sound" to "Son",
        "haptics" to "Haptique",
        "language" to "Langue",
        "backup" to "Sauvegarde",
        "restore" to "Restaurer",
        "about" to "À propos",
        "version" to "Version",
        "check_updates" to "Rechercher des mises à jour",
        "import_quiz" to "Importer un quiz",
        "paste_url" to "Coller l'URL communautaire",
        "import" to "Importer",
        "verified" to "Vérifié",
        "yes" to "Oui",
        "no" to "Non",
        "ok" to "OK",
        "loading" to "Chargement...",
        "back" to "Retour",
    )

    private val es = mapOf(
        "welcome" to "Bienvenido a Kvizo",
        "no_login_needed" to "Crea tu perfil local — no se necesita inicio de sesión",
        "pick_avatar" to "Elige un avatar",
        "username" to "Nombre de usuario",
        "status_optional" to "Estado (opcional)",
        "status_hint" to "p.ej. Maestro del Quiz",
        "bio_optional" to "Bio (opcional, máx 150)",
        "start_learning" to "Empezar a aprender",
        "err_username_required" to "Nombre de usuario requerido",
        "avatar" to "Avatar",
        "edit_profile" to "Editar perfil",
        "status_eg" to "Estado (p.ej. Maestro del Quiz)",
        "save" to "Guardar",
        "cancel" to "Cancelar",
        "delete" to "Eliminar",
        "level" to "Nivel",
        "xp" to "XP",
        "stats" to "Estadísticas",
        "quizzes_taken" to "Cuestionarios tomados",
        "accuracy" to "Precisión",
        "best_score" to "Mejor puntuación",
        "home" to "Inicio",
        "start_quiz" to "Iniciar quiz",
        "create_quiz" to "Crear quiz",
        "community" to "Comunidad",
        "leaderboard" to "Clasificación",
        "my_quizzes" to "Mis quizzes",
        "recent_quizzes" to "Quizzes recientes",
        "no_quizzes" to "Aún no hay quizzes",
        "search_quizzes" to "Buscar quizzes...",
        "question" to "Pregunta",
        "submit" to "Enviar",
        "next" to "Siguiente",
        "skip" to "Saltar",
        "correct" to "¡Correcto!",
        "wrong" to "¡Incorrecto!",
        "score" to "Puntuación",
        "finish" to "Terminar",
        "quiz_complete" to "Quiz completado",
        "your_score" to "Tu puntuación",
        "play_again" to "Jugar de nuevo",
        "quiz_title" to "Título del quiz",
        "add_question" to "Añadir pregunta",
        "option" to "Opción",
        "correct_answer" to "Respuesta correcta",
        "publish" to "Publicar",
        "settings" to "Ajustes",
        "sound" to "Sonido",
        "haptics" to "Háptica",
        "language" to "Idioma",
        "backup" to "Copia de seguridad",
        "restore" to "Restaurar",
        "about" to "Acerca de",
        "version" to "Versión",
        "check_updates" to "Buscar actualizaciones",
        "import_quiz" to "Importar quiz",
        "paste_url" to "Pegar URL de la comunidad",
        "import" to "Importar",
        "verified" to "Verificado",
        "yes" to "Sí",
        "no" to "No",
        "ok" to "OK",
        "loading" to "Cargando...",
        "back" to "Atrás",
    )

    private val de = mapOf(
        "welcome" to "Willkommen bei Kvizo",
        "no_login_needed" to "Erstelle dein lokales Profil — keine Anmeldung nötig",
        "pick_avatar" to "Avatar wählen",
        "username" to "Benutzername",
        "status_optional" to "Status (optional)",
        "status_hint" to "z.B. Quiz-Meister",
        "bio_optional" to "Bio (optional, max 150)",
        "start_learning" to "Lernen starten",
        "err_username_required" to "Benutzername erforderlich",
        "avatar" to "Avatar",
        "edit_profile" to "Profil bearbeiten",
        "status_eg" to "Status (z.B. Quiz-Meister)",
        "save" to "Speichern",
        "cancel" to "Abbrechen",
        "delete" to "Löschen",
        "level" to "Level",
        "xp" to "XP",
        "stats" to "Statistiken",
        "quizzes_taken" to "Gemachte Quizze",
        "accuracy" to "Genauigkeit",
        "best_score" to "Bestpunktzahl",
        "home" to "Start",
        "start_quiz" to "Quiz starten",
        "create_quiz" to "Quiz erstellen",
        "community" to "Community",
        "leaderboard" to "Bestenliste",
        "my_quizzes" to "Meine Quizze",
        "recent_quizzes" to "Neueste Quizze",
        "no_quizzes" to "Noch keine Quizze",
        "search_quizzes" to "Quizze suchen...",
        "question" to "Frage",
        "submit" to "Absenden",
        "next" to "Weiter",
        "skip" to "Überspringen",
        "correct" to "Richtig!",
        "wrong" to "Falsch!",
        "score" to "Punkte",
        "finish" to "Beenden",
        "quiz_complete" to "Quiz abgeschlossen",
        "your_score" to "Deine Punkte",
        "play_again" to "Nochmal spielen",
        "quiz_title" to "Quiz-Titel",
        "add_question" to "Frage hinzufügen",
        "option" to "Option",
        "correct_answer" to "Richtige Antwort",
        "publish" to "Veröffentlichen",
        "settings" to "Einstellungen",
        "sound" to "Ton",
        "haptics" to "Haptik",
        "language" to "Sprache",
        "backup" to "Backup",
        "restore" to "Wiederherstellen",
        "about" to "Über",
        "version" to "Version",
        "check_updates" to "Nach Updates suchen",
        "import_quiz" to "Quiz importieren",
        "paste_url" to "Community-URL einfügen",
        "import" to "Importieren",
        "verified" to "Verifiziert",
        "yes" to "Ja",
        "no" to "Nein",
        "ok" to "OK",
        "loading" to "Lädt...",
        "back" to "Zurück",
    )

    private val all = mapOf(
        "en" to en, "hi" to hi, "ta" to ta, "te" to te,
        "bn" to bn, "fr" to fr, "es" to es, "de" to de,
    )

    /** Localized string lookup with English fallback. */
    @JvmStatic
    fun s(key: String): String =
        all[current]?.get(key) ?: en[key] ?: key

    @JvmStatic
    fun compose(lang: String, key: String): String =
        all[lang]?.get(key) ?: en[key] ?: key
}
